import type { DisplayMode } from '@/types'

// ── Types ──────────────────────────────────────────────────────────────────────

export interface ColDef {
  /** 0 = Today, 1 = Expiry */
  frac: number
  label: string
  /** True if an earnings date falls on this column */
  isEarnings: boolean
}

export interface HeatTableProps {
  /**
   * 16 price points, descending (high → low).
   * Generated by caller: stockPrice*(1+range%) to stockPrice*(1-range%) evenly.
   */
  prices: number[]
  /**
   * 9 column definitions (Today → Expiry).
   * Caller builds these from selectedExpiry + today.
   */
  cols: ColDef[]
  /**
   * P&L matrix: matrix[colIdx][priceIdx] = USD value.
   * Caller computes via Web Worker (CALC_HEATMAP).
   */
  matrix: number[][]
  stockPrice: number
  displayMode: DisplayMode
  /** Cost basis for pct mode */
  costBasis: number
  /** Max loss for risk mode (positive USD) */
  maxLoss: number
  /** Called when a column header is clicked */
  onColClick: (frac: number) => void
}

// ── Value transform (mirrors PnlChart logic) ──────────────────────────────────

function transformVal(
  v: number,
  mode: DisplayMode,
  costBasis: number,
  maxLoss: number,
): number {
  switch (mode) {
    case 'pct':
      return costBasis !== 0 ? (v / Math.abs(costBasis)) * 100 : v
    case 'risk':
      return maxLoss > 0 ? (v / maxLoss) * 100 : v
    case 'contract':
      return v / 100
    default:
      return v
  }
}

function fmtVal(v: number, mode: DisplayMode): string {
  const sign = v >= 0 ? '+' : ''
  switch (mode) {
    case 'pct':
      return `${sign}${v.toFixed(1)}%`
    case 'risk':
      return `${sign}${v.toFixed(0)}%`
    case 'contract':
      return `${sign}$${v.toFixed(2)}`
    default:
      return v >= 0 ? `+$${v.toFixed(0)}` : `-$${Math.abs(v).toFixed(0)}`
  }
}

// ── Cell background ───────────────────────────────────────────────────────────

function cellBg(val: number, maxAbsVal: number): string {
  if (val === 0 || maxAbsVal === 0) return ''
  const intensity = Math.min(0.7, (Math.abs(val) / maxAbsVal) * 0.7)
  if (val > 0) return `rgba(10,184,122,${intensity.toFixed(3)})`
  return `rgba(232,54,74,${intensity.toFixed(3)})`
}

// ── Component ──────────────────────────────────────────────────────────────────

export function HeatTable({
  prices,
  cols,
  matrix,
  stockPrice,
  displayMode,
  costBasis,
  maxLoss,
  onColClick,
}: HeatTableProps) {
  // Transform every value to display mode
  const displayMatrix: number[][] = matrix.map((col) =>
    col.map((v) => transformVal(v, displayMode, costBasis, maxLoss)),
  )

  // Max absolute value across all cells for intensity scaling
  const allVals = displayMatrix.flat()
  const maxAbsVal =
    allVals.length > 0
      ? Math.max(Math.abs(Math.max(...allVals)), Math.abs(Math.min(...allVals)))
      : 1

  // Index of the price row closest to current stock price
  const curRowIdx = prices.reduce((best, p, i) => {
    return Math.abs(p - stockPrice) < Math.abs(prices[best] - stockPrice) ? i : best
  }, 0)

  return (
    <div
      style={{
        width: '100%',
        height: '100%',
        overflow: 'auto',
        fontFamily: 'var(--mono)',
        fontSize: 11,
        background: 'var(--surface)',
      }}
    >
      <div style={{ minWidth: 'max-content', padding: 12 }}>
        <table
          style={{
            borderCollapse: 'collapse',
            width: '100%',
            tableLayout: 'fixed',
          }}
        >
          <thead>
            <tr>
              {/* Price column header */}
              <th
                style={{
                  position: 'sticky',
                  top: 0,
                  left: 0,
                  zIndex: 20,
                  background: 'var(--surface)',
                  padding: '5px 8px 5px 10px',
                  textAlign: 'left',
                  fontSize: 10,
                  fontWeight: 600,
                  color: 'var(--t2)',
                  borderBottom: '2px solid var(--border2)',
                  whiteSpace: 'nowrap',
                  minWidth: 70,
                }}
              >
                Price
              </th>

              {cols.map((col, ci) => (
                <th
                  key={ci}
                  onClick={() => onColClick(col.frac)}
                  style={{
                    position: 'sticky',
                    top: 0,
                    zIndex: 10,
                    background: ci === 0 ? 'rgba(37,99,235,0.04)' : 'var(--surface)',
                    padding: '5px 8px',
                    textAlign: 'right',
                    fontSize: 10,
                    fontWeight: 600,
                    color: col.isEarnings ? 'var(--amber-t)' : 'var(--t2)',
                    borderBottom: '2px solid var(--border2)',
                    whiteSpace: 'nowrap',
                    cursor: 'pointer',
                    userSelect: 'none',
                  }}
                >
                  {col.label}
                </th>
              ))}
            </tr>
          </thead>

          <tbody>
            {prices.map((price, ri) => {
              const isCurRow = ri === curRowIdx
              return (
                <tr key={ri}>
                  {/* Price cell — sticky left */}
                  <td
                    style={{
                      position: 'sticky',
                      left: 0,
                      zIndex: 5,
                      background: isCurRow ? 'var(--blue-bg)' : 'var(--surface)',
                      borderRight: '2px solid var(--border2)',
                      padding: '4px 8px 4px 10px',
                      textAlign: 'left',
                      fontWeight: 600,
                      color: isCurRow ? 'var(--blue-t)' : 'var(--t1)',
                      whiteSpace: 'nowrap',
                    }}
                  >
                    ${price.toFixed(2)}
                  </td>

                  {cols.map((_, ci) => {
                    const val = displayMatrix[ci]?.[ri] ?? 0
                    const bg = cellBg(val, maxAbsVal)
                    const isFirstCol = ci === 0
                    return (
                      <td
                        key={ci}
                        style={{
                          padding: '4px 8px',
                          textAlign: 'right',
                          border: '1px solid rgba(0,0,0,0.04)',
                          whiteSpace: 'nowrap',
                          cursor: 'pointer',
                          transition: 'opacity 0.1s',
                          background: isFirstCol
                            ? bg
                              ? `${bg}`
                              : 'rgba(37,99,235,0.04)'
                            : bg || undefined,
                        }}
                        onMouseEnter={(e) => {
                          e.currentTarget.style.opacity = '0.75'
                        }}
                        onMouseLeave={(e) => {
                          e.currentTarget.style.opacity = '1'
                        }}
                      >
                        {fmtVal(val, displayMode)}
                      </td>
                    )
                  })}
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}
